name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: yarn
      
      - name: Run Build
        run: yarn build
      
      - name: Copy dist folder to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          port: ${{ secrets.DO_SSH_PORT }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "., !node_modules"
          target: "app/gobarber-deploy"
